Refactor daemons script + add startup check

diff --git a/guts/daemons b/guts/daemons
--- a/guts/daemons
+++ b/guts/daemons
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -uo pipefail
+set -euo pipefail
 
 usage="
 Usage: $(basename "$0") <command> [args...]
@@ -18,55 +18,55 @@ mkdir -p "$infdir"
 
 # main functions
 
-check () {
-    for inff in "$infdir"/*.inf; do
-        [[ -f $inff ]] || continue
-        # check whether it's a valid daemon process file
-        if [[ $(head -1 "$inff") != "$header" ]]; then
-            rm "$inff"
-            continue
-        fi
+inffile() {
+    [[ -f ${inffile} ]] || return 1
+    read -r head <"$1"
+    if [[ "${head}" != "${header}" ]]; then
+        echo "Deleting corrupted file $1" >&2
+        rm "$1"
+        return 1
+    fi
+    return 0
+}
 
-        . "$inff"               # sets pid, psline, wd & command
-        psout=$($ps "$pid")
-        if [[ $psline != "$psout" ]]; then
-            echo "Restarting $command..."
-            rm "$inff"
-            ( cd "$wd" && $command ) & # run in a subshell
+check() {
+    for inffile in "$infdir"/*.inf; do
+        inffile "${inffile}" || continue
+        source "${inffile}"     # sets pid, psline, wd & command
+        local psout
+        psout=$($ps "$pid" || true)
+        if [[ "${psline}" != "${psout}" ]]; then
+            echo "Restarting ${command[*]}..." >&2
+            rm "${inffile}"
+            (cd "$wd" && run "${command[@]}") &
         fi
     done
 }
 
-run () {
-    wd=$(pwd)
-    "$@" &                      # run command in background
-    pid=$!
-    psline=$($ps "$pid")
+run() {
+    local basename="${infdir}/${uuid}"
+    (echo -n "+ "; printf "%q " "$@"; echo) >"${basename}.log"
+    "$@" </dev/null >>"${basename}.log" 2>&1 &
+    local pid=$!
+    echo Command started, output redirected to "${basename}.log" >&2
+    local psline
+    psline=$($ps $pid || true)
     if [[ -n $psline ]]; then
-        cat >"$infdir/$pid.inf" <<EOF
-$header
-pid=$pid
-psline='$psline'
-wd='$wd'
-command='$0 run$(printf ' "%s"' "$@")'
-logfile='$$.log'
-EOF
+        local wd="${PWD}"
+        local command=("$@")
+        (echo "${header}"; declare -p command pid psline wd) >"${basename}.inf"
         wait $pid
-        rm "$infdir/$pid.inf"
+        rm "${basename}.inf"
+    else
+        echo "Process line not found, command terminated already?" >&2
     fi
 }
 
-list () {
-    for inff in "$infdir"/*.inf; do
-        [[ -f $inff ]] || continue
-        # check whether it's a valid daemon process file
-        if [[ $(head -1 "$inff") != "$header" ]]; then
-            rm "$inff"
-            continue
-        fi
-
-        . "$inff"               # sets pid, psline, wd & command
-        echo "$psline"
+list() {
+    for inffile in "${infdir}"/*.inf; do
+        inffile "${inffile}" || continue
+        source "${inffile}"     # sets pid, psline, wd & command
+        printf "%q " "${command[@]}"; echo
     done
 }
 
@@ -74,12 +74,12 @@ if [[ -z $1 ]]; then
     set help
 fi
 
-cmd=$1; shift
+cmd="$1"; shift
+uuid="$(uuidgen)"
 case $cmd in
     (help)  echo "$usage" ;;
-    (check) check ;;
-    (run)   run "$@" </dev/null >"$infdir/$$.log" 2>&1 &
-            echo Command started, output redirected to "$infdir/$$.log" ;;
-    (list)  list ;;
+    (check) check "$@" ;;
+    (run)   run "$@" & ;;
+    (list)  list "$@" ;;
     (*)     echo "$(basename "$0"): unknown command: $cmd"; exit 1 ;;
 esac
